version: '3.9'

services:
  web:
    image: httpd:2.4
    container_name: my_static_site
    ports:
      - "8080:80"
    volumes:
      - ./website:/usr/local/apache2/htdocs/
    restart: unless-stopped